### ISSUE TITLE
didUpdateWidget fails with error

### ISSUE THREAD

**Issue by vasilich6107** [salim-lachdhaf/searchable_dropdown#208]
Hi. This code 

```
@override
  void didUpdateWidget(DropdownSearch<T> oldWidget) {
    List<T?> oldSelectedItems =
        isMultiSelectionMode ? oldWidget.selectedItems : []
          ..add(oldWidget.selectedItem);

    List<T?> newSelectedItems = isMultiSelectionMode ? widget.selectedItems : []
      ..add(widget.selectedItem);

    if (oldSelectedItems != newSelectedItems) {
      _selectedItemsNotifier.value = List.from(newSelectedItems);
    }
    super.didUpdateWidget(oldWidget);
  }
```

fails with error

```
The following _TypeError was thrown building NotificationListener<KeepAliveNotification>:
type 'Null' is not a subtype of type 'String' of 'value'

The relevant error-causing widget was: 
  ListView file:///Users/vasilich/IdeaProjects/searchable_dropdown/example/lib/main.dart:39:18
When the exception was thrown, this was the stack: 
#0      List.add (dart:core-patch/growable_array.dart)
#1      DropdownSearchState.didUpdateWidget (package:dropdown_search/dropdown_search.dart:410:13)
#2      StatefulElement.update (package:flutter/src/widgets/framework.dart:4761:57)
#3      Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#4      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6090:14)
```

How to reproduce

- start example project
- change anything in `main.dart`
- save
- on hot reload `didUpdateWidget` fails

**Comment by salim-lachdhaf** [comment]
fixed in beta2

**Comment by vasilich6107** [comment]
Thanks for quick fixes
