### ISSUE TITLE
Text editing controller is disposed without me calling dispose method and not leaving the page

### ISSUE THREAD

**Issue by komritza** [salim-lachdhaf/searchable_dropdown#498]
**Describe the bug**
When I come to the page where I use this package I am getting an error when I open the dropdown menu for the second time. To be more specific, opening for the first time and searching and selecting an item works perfect, but when I click again to change the selected item, I am getting following error:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building DefaultTextStyle(debugLabel: (englishLike bodyMedium
flutter: 2014).merge((blackCupertino bodyMedium).merge(unknown)), inherit: false, color: Color(0xffffffff),
flutter: family: Lato-Black, size: 18.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none,
flutter: softWrap: wrapping at box width, overflow: clip):
flutter: A TextEditingController was used after being disposed.
flutter: Once you have called dispose() on a TextEditingController, it can no longer be used.
flutter:
flutter: The relevant error-causing widget was:
flutter:   Material
flutter:   Material:file:///Users/markoabacus/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/dropdown_search-5.0.3/lib/src/widgets/popupMenu.dart:119:18
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:147:9)
flutter: #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:154:6)
flutter: #2      ChangeNotifier.addListener (package:flutter/src/foundation/change_notifier.dart:207:27)
flutter: #3      SelectionWidgetState.initState (package:dropdown_search/src/widgets/selection_widget.dart:59:25)
flutter: #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
flutter: #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
flutter: ...     Normal element mounting (214 frames)
flutter: #219    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
flutter: #220    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
flutter: #221    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
flutter: #222    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964:32)
flutter: #223    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
flutter: #224    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
flutter: #226    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
flutter: #227    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
flutter: #228    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
flutter: #229    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
flutter: #231    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
flutter: #232    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
flutter: #233    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
flutter: #235    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
flutter: #236    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
flutter: #237    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
flutter: #238    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #239    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
flutter: #240    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
flutter: #242    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
flutter: #243    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
flutter: #244    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
flutter: #245    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #246    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
flutter: #247    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #248    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
flutter: #249    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
flutter: #251    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
flutter: #252    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
flutter: #253    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
flutter: #254    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
flutter: #255    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
flutter: #256    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
flutter: #257    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
flutter: #258    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
flutter: #259    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
flutter: #260    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
flutter: #261    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
flutter: #262    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
flutter: #263    _invoke (dart:ui/hooks.dart:148:13)
flutter: #264    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
flutter: #265    _drawFrame (dart:ui/hooks.dart:115:31)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**To Reproduce**
I couldn't reproduce this bug with the example app, but I am using this package in the production app since a long time ago and this was never an issue. I suddenly noticed it today, while doing some UI changes.

**Expected behavior**
I should be able to reopen dropdown menu.

**Screenshots**
![Simulator Screen Shot - iPhone 13 Pro - 2022-10-25 at 19 54 23](https://user-images.githubusercontent.com/44901103/197846830-ec52091a-4e2a-4f8f-b664-0c546528de5e.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone13 Pro Emulator]
 - OS: [e.g. iOS 15.0]
- Flutter version 3.3.3

**Additional context**
Widget code:
```
Widget _buildCostCenterEditField() => Container(
        color: _appTheme.white,
        padding: const EdgeInsets.symmetric(horizontal: 18),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding: const EdgeInsets.only(top: 10),
              child: Text(
                _facade.l10n.costCenter.toUpperCase(),
                style: Theme.of(context).textTheme.caption,
              ),
            ),
            Container(
              padding: const EdgeInsets.only(bottom: 15),
              child: Row(
                children: [
                  Expanded(
                    child: DropdownSearch<CostCenter>(
                      key: _dropdownButtonCostCenterKey,
                      items: _facade.costCenters,
                      popupProps: PopupProps.menu(
                        showSearchBox: true,
                        fit: FlexFit.loose,
                        constraints: const BoxConstraints(maxHeight: 400),
                        emptyBuilder: (context, noResults) => Center(
                          child: Text(_facade.l10n.noResultsFound,
                              style: Theme.of(context)
                                  .textTheme
                                  .subtitle1!
                                  .copyWith(color: _appTheme.greyBlue)),
                        ),
                        itemBuilder: (context, costCenter, _) =>
                            _buildCostCenter(context, costCenter),
                        menuProps: MenuProps(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                        searchFieldProps: TextFieldProps(
                          controller: _searchCostCenterController,
                          autofocus: true,
                          autocorrect: false,
                          padding: const EdgeInsets.symmetric(horizontal: 25),
                          decoration: InputDecoration(
                            enabledBorder: UnderlineInputBorder(
                              borderSide: BorderSide(color: _appTheme.greyBlue),
                            ),
                            focusedBorder: UnderlineInputBorder(
                              borderSide: BorderSide(color: _appTheme.greyBlue),
                            ),
                            suffixIcon: IconButton(
                              icon: Icon(
                                Icons.clear,
                                color: _appTheme.greyBlue,
                              ),
                              onPressed: _searchCostCenterController.clear,
                            ),
                          ),
                        ),
                      ),
                      dropdownButtonProps: DropdownButtonProps(
                        icon: Icon(
                          Icons.keyboard_arrow_down,
                          color: _appTheme.greyBlue,
                        ),
                      ),
                      dropdownDecoratorProps: DropDownDecoratorProps(
                        dropdownSearchDecoration: InputDecoration(
                          label: Text(_facade.selectedCostCenterName.isNotEmpty
                              ? _facade.selectedCostCenterName
                              : _facade.l10n.select),
                          floatingLabelBehavior:
                              _facade.selectedCostCenterName.isNotEmpty
                                  ? FloatingLabelBehavior.never
                                  : FloatingLabelBehavior.always,
                          focusedBorder: InputBorder.none,
                          labelStyle: Theme.of(context)
                              .textTheme
                              .subtitle1!
                              .copyWith(color: _appTheme.greyBlue),
                          contentPadding: EdgeInsets.zero,
                        ),
                      ),
                      onChanged: (costCenter) =>
                          _facade.selectCostCenter(costCenter!),
                      itemAsString: (cc) => _facade.selectedCostCenterName,
                      selectedItem: _facade.selectedCostCenter,
                    ),
                  )
                ],
              ),
            ),
          ],
        ),
      );
```

Any help would be highly appreciated, thanks!

**Comment by nblum37** [comment]
Hi,
I see the same issue and am also looking for a solution. Thank you :)

**Comment by ckovamees** [comment]
I have this issue too. Is there any other way to get the search field text without the controller?
