### ISSUE TITLE
Unable to use dropdown_search within MaterialApp builder

### ISSUE THREAD

**Issue by ckrc** [salim-lachdhaf/searchable_dropdown#54]
I am getting an error if I use this control directly within MaterialApp builder

`Material(
                child: Scaffold(
                  body: Builder(
                    builder: (_) => DropdownSearch<String>(
                        mode: Mode.MENU,
                        showSelectedItem: true,
                        items: [
                          "Brazil",
                          "Italia (Disabled)",
                          "Tunisia",
                          'Canada'
                        ],
                        label: "Menu mode",
                        hint: "country in menu mode",
                        popupItemDisabled: (String s) => s.startsWith('I'),
                        onChanged: print,
                        selectedItem: "Brazil"),
                  ),
                ),`

**This render fine but when I press the dropdown and I get the following error**

TypeError: Cannot read property 'context' of null
    at _DropdownSearchState.new.[_openMenu] (http://127.0.0.1:8080/packages/dropdown_search/src/selectDialog.dart.lib.js:3455:72)
    at _DropdownSearchState.new._selectSearchMode (http://127.0.0.1:8080/packages/dropdown_search/src/selectDialog.dart.lib.js:3485:34)
    at _selectSearchMode.next (<anonymous>)
    at runBody (http://127.0.0.1:8080/dart_sdk.js:37699:34)
    at Object._async [as async] (http://127.0.0.1:8080/dart_sdk.js:37730:7)
    at _DropdownSearchState.new.[_selectSearchMode] (http://127.0.0.1:8080/packages/dropdown_search/src/selectDialog.dart.lib.js:3482:22)
    at http://127.0.0.1:8080/packages/dropdown_search/src/selectDialog.dart.lib.js:3405:307
    at tap.TapGestureRecognizer.new.invokeCallback (http://127.0.0.1:8080/packages/flutter/src/gestures/recognizer.dart.lib.js:189:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://127.0.0.1:8080/packages/flutter/src/gestures/tap.dart.lib.js:395:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://127.0.0.1:8080/packages/flutter/src/gestures/tap.dart.lib.js:201:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://127.0.0.1:8080/packages/flutter/src/gestures/tap.dart.lib.js:148:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://127.0.0.1:8080/packages/flutter/src/gestures/recognizer.dart.lib.js:448:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://127.0.0.1:8080/packages/flutter/src/gestures/pointer_router.dart.lib.js:74:9)
    at http://127.0.0.1:8080/packages/flutter/src/gestures/pointer_router.dart.lib.js:109:26
    at LinkedMap.new.forEach (http://127.0.0.1:8080/dart_sdk.js:24816:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://127.0.0.1:8080/packages/flutter/src/gestures/pointer_router.dart.lib.js:106:29)
    at pointer_router.PointerRouter.new.route (http://127.0.0.1:8080/packages/flutter/src/gestures/pointer_router.dart.lib.js:98:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://127.0.0.1:8080/packages/flutter/src/gestures/binding.dart.lib.js:306:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://127.0.0.1:8080/packages/flutter/src/gestures/binding.dart.lib.js:289:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://127.0.0.1:8080/packages/flutter/src/rendering/layer.dart.lib.js:5973:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://127.0.0.1:8080/packages/flutter/src/gestures/binding.dart.lib.js:260:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://127.0.0.1:8080/packages/flutter/src/gestures/binding.dart.lib.js:233:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://127.0.0.1:8080/packages/flutter/src/gestures/binding.dart.lib.js:222:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://127.0.0.1:8080/packages/flutter/src/gestures/binding.dart.lib.js:212:65)
    at Object._invoke1 (http://127.0.0.1:8080/dart_sdk.js:176547:7)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://127.0.0.1:8080/dart_sdk.js:172276:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://127.0.0.1:8080/dart_sdk.js:159053:24)
    at http://127.0.0.1:8080/dart_sdk.js:159442:26
    at http://127.0.0.1:8080/dart_sdk.js:159401:16
    at http://127.0.0.1:8080/dart_sdk.js:159154:11

Could someone please help?

**Comment by ckrc** [comment]
I am able to workaround the issue with the solution provided here - https://www.gitmemory.com/issue/flutter/flutter/45512/558485205

which

**Comment by ckrc** [comment]
@salim-lachdhaf Could you please share some insights into the issue described above?

Basically putting the DropDownSearch within the builder of MaterialApp, and clicking the dropdown control will reproduce the error. 

I think the control is not able to determine the size, perhaps? Not sure how to resolve this issue though... 

MaterialApp(
      title: 'Example App',
      theme: _themeData(),
      initialRoute: isAuthenticated ? '/accounts' : '/login',
      builder: (context, child) => Material(
        child: Scaffold(
          body: DropdownSearch<String>(
              mode: Mode.MENU,
              showSelectedItem: true,
              items: ["Brazil", "Italia (Disabled)", "Tunisia", 'Canada'],
              label: "Menu mode",
              hint: "country in menu mode",
              popupItemDisabled: (String s) => s.startsWith('I'),
              onChanged: print,
              selectedItem: "Brazil"),
        ),
      ),
....

**Comment by salim-lachdhaf** [comment]
Could you try add scaffold as parent of the widget

**Comment by ckrc** [comment]
@salim-lachdhaf I have already added scaffold as parent of the widget and still getting the same error. Is there anything else you can suggest?

**Comment by salim-lachdhaf** [comment]
Could you past the full example

**Comment by salim-lachdhaf** [comment]
Otherwies , put the dropdownsearch into separete stateless or statefull widget and call that widget as your dropdown widget to gain the context

**Comment by ckrc** [comment]
@salim-lachdhaf I have tried wrapping the dropdownsearch into a separate statefull widget and that doesn't help. Same error remains. 

I think the probably is I am trying to call the dropdownsearch widget from MaterialApp builder, and dropdownsearch is sitting above the MaterialApp perhaps?

**Comment by ckrc** [comment]
```
// Get the render object of the overlay used in `Navigator` / `MaterialApp`, i.e. screen size reference
 final RenderBox overlay = Overlay.of(context).context.findRenderObject();
```

Overlay.of(context) is returning null

**Comment by ckrc** [comment]
I think the problem I am getting is probably similar to this - https://github.com/flutter/flutter/issues/45512

For what I need, I can't do that in MaterialPageRoute so the solution given in that url would not work for me

**Comment by salim-lachdhaf** [comment]
That is exactly your issue.
As solution, i suggest to keep the builder and in the paramter home pass your statefull or stateless widget that contains your logic.
Exactly like the given example of the plugin just redesign it as your need or your logic
